config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  get 'home/index'

  get 'home/about'

  resources :regions do
    resources :embroderies
  end

end

app/models/embrodery.rb
class Embrodery < ActiveRecord::Base
  belongs_to :region
  mount_uploader :image, AvatarUploader
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :embroderies
  mount_uploader :image, AvatarUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale

private

  def set_locale
    I18n.locale = params[:locale] if params[:locale].present?
  end
end

app/controllers/embroderies_controller.rb
class EmbroderiesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy ]

  def index

  end

  def show
    @embroderies = Embrodery.find(params[:id])
  end

  def new
    @region = Region.find(params[:region_id])
  end

  def create
    @region = Region.find(params[:region_id])
    @embrodery = @region.embroderies.create(embrodery_params)

    if @embrodery.save
      redirect_to region_embroderies_path(@embrodery)
    else
      render 'new'
    end
  end

  def destroy
     @region = Region.find(params[:region_id])
     @embrodery = @region.embroderies.find(params[:id])
     @embrodery.destroy
     redirect_to region_path(@region)
  end

  private
  def embrodery_params
    params.require(:embrodery).permit(:name, :image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController

  def index
    @regions = Region.order(name: :asc)
  end

  def show
    @region = Region.find(params[:id])
    @embroderies = @region.embroderies.page(params[:page]).per(6)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/embroderies_helper.rb
module EmbroderiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/embroderies/index.html.erb
<h1>Sucsessfully upload your model.</h1>
<h2>You can see your model here!</h2>

app/views/embroderies/new.html.erb
<div class = "container">
  <div class = "row well-bg">
    <div class = "col-md-4 col-md-offset-4">
      <h2 class = "title-add">Add new model</h2>
      <br>
      <br>
      <%= form_for ([@region, @region.embroderies.build]) do |f| %>

          <div class="field form-group">
            <%= f.text_field :name, class: 'form-control', placeholder: "Name" %>
          </div>

          <div class="field form-group">
            <%= f.file_field :image %>
          </div>
        <br>
        <p>
          <%= f.submit "Add Model", class: 'btn btn-success' %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/embroderies/show.html.erb
<div class = "container">
  <div class="row wrapper">
    <div class="col-md-6 name-single-show navbar-left"><%= @embroderies.name %></div>
    <div class = "col-md-6 navbar-right">
      <%= link_to 'BACK', :back, class: "back-btn btn4" %>
      <%= link_to 'DELETE', (@embrodery),
                 method: :delete,
                 data: { confirm: 'Are you sure?' }, class: "delete-btn btn4" %>
    </div>
    <div class="row">
      <div class="col-md-12 wrap-show-img">
        <%= image_tag @embroderies.image, class: "img-single-show" %>
      </div>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class = 'bg-about bg container'>
  <div class = "row">
    <div class = "col-md-12">
      <div class = "wraped-about">

        <%= t('about.html') %>
        
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class = "container-fluid">
  <div class = "container">
    <div class = "row clearfix">
      <div class = "col-md-12">
        <div class = "p-home">
          <%= t ('home.html') %>
        </div>
      </div>
      <div class = "col-md-12">
        <div class = "bg-div">
          <%= image_tag ("horo1.JPG"), class: "img-div" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vezba</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "favi.png"%>
</head>
<body>
  <nav class="navbar navbar-default">
      <div class="row container-fluid">
        <p class="notice"><%= notice %></p>
        <!-- <p class="alert"><%= alert %></p> -->
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="col-md-3 navbar-header">
          <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button> -->
            <%= link_to (image_tag "Logo.png", class: "brand navbar-left" ), home_index_path %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="col-md-6">
          <ul class="nav nav-menu-middle">
            <li><%= link_to t("menu.home"), home_index_path, class: "menu-btn" %></li>
            <li><%= link_to t("menu.about"), home_about_path, class: "menu-btn #{current_page?(home_about_path) ? "current" : nil }" %></li>
            <li><%= link_to t("menu.models"), regions_path(:region_id), class: "menu-btn #{current_page?(regions_path(:region_id)) ? "current" : nil }" %></li>
            <!-- <li><%= link_to "BLOG", regions_path(:region_id), class: "menu-btn" %></li> -->
            <!-- <li><%= link_to "CONTACTS", regions_path(:region_id), class: "menu-btn" %></li> -->
          </ul>
        </div>

        <div class = "hamburger-div">
          <i id="nav_bar_toggle" class="fa fa-bars fa-2x visible-sm visible-xs pull-right menu-hamburger navbar-toggle" aria-hidden="true"></i>
        </div>

        <div class = "col-md-3 nav-right">
          <ul class=" nav-menu-right navbar-right">
            <% if !user_signed_in? %>
              <li><%= link_to "Log in", new_user_session_path, class: "button-user btn3", metod: :get %></li>
              <li><%= link_to "Sign up", new_user_registration_path, class: "button-user btn3" %></li>
            <% else %>
              <li><%= link_to "Log out", destroy_user_session_path, class: "button-user btn3", method: :delete %></li>
            <% end %>
            <li><a class = "social-btn" href="https://www.facebook.com/groups/vezba/">f</a></li>
            <li class="fb-en">

            </li>
            <li>
              <%
                current_locale = I18n.locale
                toggle_locale  = current_locale == :en ? 'bg' : 'en'
                current_path   = url_for(params.merge(locale: toggle_locale))
              %>
              <%= link_to toggle_locale,   "#{current_path}", id: "myBtn", class: "social-btn" %>
          </ul>

          <div id="myModal" class="modal">
            <div class="modal-content">
              <div class="modal-header">
                <span class="close">&times;</span>
                <h2 class="modal-title">Choose Language</h2>
              </div>
              <div class="row modal-body">
                <div class = "col-md-4 col-md-offset-2">
                  <%= image_tag "Bulgaria.jpg", class:"logo" %>
                  <div class = "modal-button"><%= link_to_unless_current "Bulgarian", locale: "bg" %></div>
                </div>
                <div class = "col-md-4">
                  <%= image_tag "english.jpg", class:"logo" %>
                  <div class = "modal-button"><%= link_to_unless_current "English", locale: "en" %></div>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </nav>


      <%= yield %>


<footer class="footer">
  <div class="container-fluid">
    <p>Created By <a href="http://gloryangelova.com">Gloria Angelova</a></p>
  </div>
</footer>

</body>
</html>

app/views/regions/index.html.erb
<div class = "container region-container">
  <div class = "row wrap-div-region">
    <% @regions.each do |region| %>
      <div class = "col-md-4">
        <div class = "hovereffect">
          <%= link_to (image_tag region.image,  class:"img-responsive-region"), region %>
          <%= link_to region do %>
            <div class = "overlay">
              <p class = "region-title"><%= region.name %></p>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/regions/show.html.erb
<div class="container">
  <div class="row ">
    <div class = " row wrap-div">
      <div class="col-md-5 region-div"><%= image_tag @region.image, class: "img-responsive-region" %></div>
      <div class="col-md-7">
        <div clas = "row">
          <div class="col-md-12 text-box-region">
            <h2 class = "reg-name-show"><%= @region.name %></h2>
            <div class = "text-region"><%= @region.description %></div>
            <br>
            <br>
            <%= link_to "ADD MODEL", new_region_embrodery_path(@region), class: "button-add btn1" %>
          </div>
        </div>
      </div>
    </div>

    <div class = "row wraped-imgs">
      <div class = "all col-md-12">
        <div class = "row clearfix">
          <% @embroderies.each do |embrodery| %>
            <div class = "col-md-4 wraped-show-img">
              <div class = "row ul-list">
                <div class = "div-show"><%= link_to (image_tag embrodery.image, class: "img-show" ), region_embrodery_path(embrodery.region_id, embrodery) %></div>
                <div class = "title-embrodery">
                  <p class = "e-name"><%= embrodery.name %></p>
                  <p class = "e-name"><%= link_to "View", region_embrodery_path(embrodery.region_id, embrodery), class: "button-show btn2" %></p>
                </div>
                </div>

            </div>
           <% end %>
        </div>
      </div>
      <%= paginate @embroderies, :left => 1, :right => 3 %>
    </div>
  </div>
</div>